---
title: "Mamary Gland Development Exploratory Data Analysis"
author: "Karsten Bach"
date: '`r Sys.Date()`'
output:
  html_notebook:
    toc: true
    toc_depth: 2
    toc_float: true
    theme: united
    highlight: tango
---
***
# Load Data and Packages
```{r, message=FALSE}
library(scran)
library(dplyr)
library(knitr)
library(ggplot2)
library(cowplot)
library(reshape2)
library(Rtsne)
source("functions.R")
dataList <- readRDS("../data/Robjects/secondRun_2500/ExpressionList.rds")
m <- dataList[["counts"]]
pD <- dataList[["phenoData"]]
fD <- dataList[["featureData"]]
rm(dataList)
```
# Overview over the data

## 
```{r}
smry <- read.csv("../data/CellRangerData/secondRun_2500/Summary.csv")
smry <- melt(smry)
smry$SampleID <- factor(smry$SampleID,levels=c("NP1","NP2","G1","G2","L1","L2","PI1","PI2"))
smPlot <- ggplot(smry, aes(x=as.factor(SampleID),y=value,fill=SampleID)) +
    geom_bar(stat="identity") +
    facet_wrap(~variable, scale="free") +
    theme(axis.text.x=element_blank()) +
    xlab("Sample")


smPlot
```

## Number of Cells
We sequenced more cells than expected with a total of `r ncol(m)` cells.
```{r}
kable(t(as.matrix(table(pD$SampleID))))
kable(t(as.matrix(table(pD$Condition))))
```

# Quality Overview
## Sequencing Depth and Genes detected
```{r}
pD$UmiSums<- colSums(m)
pD$GenesDetected <- colSums(m!=0)
genesDetected <- ggplot(pD, aes(x=SampleID,y=GenesDetected,fill=Condition)) +
    geom_violin(draw_quantiles=0.5)+
    scale_y_log10() 
LibrarySize <- ggplot(pD, aes(x=SampleID,y=UmiSums,fill=Condition)) +
    geom_violin(draw_quantiles=0.5)+
    scale_y_log10() 
gdLibSize <- ggplot(pD, aes(y=log10(GenesDetected), x=log10(UmiSums), color=Condition, shape=Replicate)) +
    geom_point() +
    geom_smooth(method=loess,inherit.aes=FALSE,aes(y=log10(GenesDetected),x=log10(UmiSums))) 
genesDetected
LibrarySize
gdLibSize
```

## Genewise QC
```{r, fig.height=8}
ntop <- 50 
mRel <- t(t(m)/colSums(m))
rownames(mRel)  <- fD$symbol
topExpressed <- rowMedians(mRel)
names(topExpressed) <- rownames(mRel)
topExpressed <- topExpressed %>% sort(.,decreasing=TRUE) %>% names
plotData <- t(mRel)[,topExpressed[1:ntop]] %>%
    reshape2::melt() %>%
    rename(Cell=Var1,
	   Gene=Var2,
	   RelativeExpression=value)
topGenes <- ggplot(plotData, aes(x=Gene, y=RelativeExpression)) +
    geom_boxplot() +
    coord_flip() 
freqOfExp <- m!=0
rownames(freqOfExp) <- fD$symbol
freqOfExp <- sort(rowSums(freqOfExp)/ncol(freqOfExp),decreasing=TRUE)
plotData <- data.frame("Gene"=names(freqOfExp),"Frequency"=freqOfExp)
topFreq <- ggplot(plotData[1:ntop,], aes(x=factor(Gene,levels=Gene),y=Frequency)) +
    geom_bar(stat="identity") +
    coord_flip() +
    xlab("Gene") 
topGenes
topFreq
rm(mRel)
```

## Cell Viability
```{r}
mMito <- m[fD$Mitochondrial,]
idtop <- fD[fD$symbol %in% names(freqOfExp)[1:ntop],"id"]
mTop <- m[idtop,]!=0
pD$prcntTop <- colSums(mTop)/ntop
pD$prcntMito <- colSums(mMito)/colSums(m)
cellViability <- ggplot(pD, aes(x=prcntMito, y=GenesDetected, color=Condition, shape=Replicate))+
    geom_point() 
cellViability
prcntTop <- ggplot(pD, aes(x=prcntTop, y=GenesDetected, color=Condition, shape=Replicate))+
    geom_point() 
prcntTop
rm(mMito)
rm(mTop)
```

## Thresholds

```{r}
smryByGroup <- group_by(pD,Condition) %>%
    summarize(medianPrcntMito=median(prcntMito),
	      madPrcntMito=mad(prcntMito),
	      threshold_PrcntMito=0.05,
	      mGenesDetected=median(log10(GenesDetected)),
	      madGenesDetected=mad(log10(GenesDetected)),
	      threshold_GenesDetected=mGenesDetected-2*madGenesDetected,
	      mUmiSums=median(log10(UmiSums)),
	      madUmiSums=mad(log10(UmiSums)),
	      threshold_UmiSums=mUmiSums-2*madUmiSums) %>%
    select(Condition,starts_with("threshold")) 
kable(smryByGroup)

thrGenesDetected <- median(log10(pD$GenesDetected))-3*mad(log10(pD$GenesDetected))
thrUmiSums <- median(log10(pD$UmiSums))-3*mad(log10(pD$UmiSums))
```

# Per Condition
```{r}
MitoCutOff <- 0.05
gdHist <- ggplot(pD, aes(x=GenesDetected,y=..density..)) +
    geom_histogram(fill="white",color="black") +
    geom_vline(data=smryByGroup,aes(xintercept=10^threshold_GenesDetected),color="red",lty="longdash") +
    scale_x_log10() +
    xlab("Total number of genes detected") +
    facet_wrap(~Condition) 

libSizeHist <- ggplot(pD, aes(x=UmiSums,y=..density..)) +
    geom_histogram(fill="white",color="black") +
    geom_vline(data=smryByGroup,aes(xintercept=10^threshold_UmiSums),color="red",lty="longdash") +
    scale_x_log10() +
    facet_wrap(~Condition) +
    xlab("Total number of unique molecules") 

cellViability <- cellViability %+% pD
cellViability <- cellViability + 
    annotate("rect",ymin=-Inf, ymax=Inf, xmax=Inf, xmin=MitoCutOff,
	     fill="grey", alpha=0.3) 

gdHist
libSizeHist
cellViability
```

# In total

```{r}
gdHist <- ggplot(pD, aes(x=GenesDetected,y=..density..)) +
    geom_histogram(fill="white",color="black") +
    geom_vline(aes(xintercept=10^thrGenesDetected),color="red",lty="longdash") +
    scale_x_log10() +
    xlab("Total number of genes detected") 

libSizeHist <- ggplot(pD, aes(x=UmiSums,y=..density..)) +
    geom_histogram(fill="white",color="black") +
    geom_vline(aes(xintercept=10^thrUmiSums),color="red",lty="longdash") +
    scale_x_log10() +
    xlab("Total number of unique molecules") 


gdHist
libSizeHist
pD2 <- mutate(pD,
	     PassViability=prcntMito < MitoCutOff,
	     PassGenesDet=GenesDetected > thrGenesDetected ,
	     PassLibSize=UmiSums > thrUmiSums,
	     PassAll= PassViability & PassGenesDet & PassLibSize)
table(pD2$PassViability,pD2$SampleID)
table(pD2$PassGenesDet,pD2$SampleID)
table(pD2$PassLibSize,pD2$SampleID)
table(pD2$PassAll,pD2$SampleID)
```

```{r}
#Thresholding per group
#inititae Df
pD <- mutate(pD,
	     ThresholdViability = 0,
	     ThresholdGenesDet = 0,
	     ThresholdLibSize = 0)

grps <- as.character(unique(pD$Condition))
for (grp in grps) {
    thrs <- filter(smryByGroup, Condition==grp) %>% select(-Condition) %>% t() %>% as.vector()
    names(thrs) <- filter(smryByGroup, Condition==grp) %>% select(-Condition) %>% t() %>% rownames()
    pD <- mutate(pD,
		 ThresholdViability= ifelse(Condition==grp, MitoCutOff, ThresholdViability),
		 ThresholdGenesDet= ifelse(Condition==grp, 10^thrs["threshold_GenesDetected"],ThresholdGenesDet),
		 ThresholdLibSize= ifelse(Condition==grp, 10^thrs["threshold_UmiSums"],ThresholdLibSize))
}

pD <- mutate(pD,
	     PassViability=prcntMito < ThresholdViability,
	     PassGenesDet=GenesDetected > ThresholdGenesDet,
	     PassLibSize=UmiSums > ThresholdLibSize,
	     PassAll= PassViability & PassGenesDet & PassLibSize)
table(pD$PassViability,pD$SampleID)
table(pD$PassGenesDet,pD$SampleID)
table(pD$PassLibSize,pD$SampleID)
table(pD$PassAll,pD$SampleID)
```

## Index Swapping

```{r}
barcodes <- as.character(pD$barcode)
spt <- strsplit(barcodes, split = "-", fixed = T)
pD$sample <- sapply(spt, function(x) x[2])
pD$bcs <- sapply(spt, function(x) x[1])
pD.add <- data.frame(bcs=names(table(pD$bcs)),
		     bc.obs=(table(pD$bcs)))
pD.add <- pD.add[,-2]
pD <- dplyr::left_join(pD,pD.add)

# P1
p1 <- ggplot(pD, aes(x=SampleID, fill=as.factor(bc.obs.Freq))) +
    geom_bar() +
    #     ggtitle("Samples contain many shared barcodes") +
    scale_fill_discrete(name="Times barcode observed") +
    theme(legend.position="bottom",
	  legend.direction="horizontal")

compare <- function(barcodes, samples) {
    out <- NULL
    ids <- levels(samples)
    combs <- combn(ids,m=2, simplify=FALSE)
    for (i in seq_along(combs)) {
	comb <- combs[[i]]
	s1 <- comb[1]
	s2 <- comb[2]
	bc1 <- as.character(barcodes[samples==s1])
	bc2 <- as.character(barcodes[samples==s2])
	x <- length(intersect(bc1,bc2))
	m <- length(bc1)
	n <- 750000
	k <- length(bc2)
	p.val <- phyper(q=x-1,m=m,n=n,k=k,lower.tail=FALSE)
	tmp <- data.frame(s1=s1,
			  s2=s2,
			  n1=m,
			  n2=k,
			  shared=x,
			  p.val=p.val)
	out <- rbind(out,tmp)
    }
    return(out)
}

# P2
compDf <- compare(pD$bcs, pD$SampleID)
p2 <- ggplot(compDf, aes(x=shared, y=-log10(p.val))) +
    geom_point() +
    xlab("# shared Barcodes") +
    ylab("-log10(P)") +
    geom_hline(yintercept=2,lty="dashed",color="red") 
p1
p2
```

#Apply Thresholds

```{r}
pD <- filter(pD, PassAll)
m <- m[,as.character(pD$barcode)]

#Thresholding on lowly expressed genes
isexpThreshold <- 10
expThreshold <- 50*isexpThreshold
keep1 <- rowSums(m!=0) > isexpThreshold
keep2 <- rowSums(m) > expThreshold
fD$keep <- keep1 & keep2
m <- m[fD$keep,]
fD <- fD[fD$keep,]
#Final matrix
dim(m)
```


# Normalization and Highly Variable Gene Selection
```{r}
clusters <- quickCluster(m,method="igraph")
pD$sf <- computeSumFactors(m,clusters=clusters)
plot(log10(colSums(m))~log10(pD$sf),main="Library Size versus Size Factors")
m <- t(t(m)/pD$sf)
# 
#HVG definition by Brennecke
brennecke <- BrenneckeHVG(m.norm,fdr=0.1,minBiolDisp=0.25)
fD$highVar <- fD$id %in% brennecke

VarPlot <- ggplot(fD, aes(x=meanExpression,y=CV2, color=highVar)) +
    geom_point() +
    scale_x_log10() +
    scale_y_log10() +
    theme_bw()
VarPlot
```

# First Visualization
```{r}
fPCA <- log2(t(m.norm[fD.filtered$highVar,])+1)
fPCA <- scale(fPCA,scale=TRUE,center=TRUE)
pc <- prcomp(fPCA)
set.seed(rnd_seed)
tsn <- Rtsne(fPCA,perplexity=25)

pD.filtered$PC1 <- pc$x[,1]
pD.filtered$PC2 <- pc$x[,2]
pD.filtered$PC3 <- pc$x[,3]
pD.filtered$PC4 <- pc$x[,4]
pD.filtered$tSNE1 <- tsn$Y[,1]
pD.filtered$tSNE2 <- tsn$Y[,2]

Acta2 <- filter(fD.filtered, symbol=="Acta2") %>% .$id
pD.filtered$Acta2 <- t(m.norm)[,Acta2]
Csn2 <- filter(fD.filtered, symbol=="Csn2") %>% .$id
pD.filtered$Csn2 <- t(m.norm)[,Csn2]
# 
pcaPlot <- ggplot(pD.filtered, aes(x=PC1, y=PC2, color=Condition, shape=Replicate)) +
    geom_point(alpha=0.8,size=2) +
    theme_bw() 
pcaPlot

pcaPlot <- ggplot(pD.filtered, aes(x=PC1, y=PC3, color=log2(Csn2+1), shape=Replicate)) +
    geom_point(alpha=0.8,size=2) +
    theme_bw() 
pcaPlot

pcaPlot <- ggplot(pD.filtered, aes(x=PC1, y=PC2, color=log2(Acta2+1), shape=Replicate)) +
    geom_point(alpha=0.8,size=2) +
    theme_bw() 
pcaPlot

tsnePlot <- ggplot(pD.filtered, aes(x=tSNE1, y=tSNE2, color=Condition, shape=Replicate)) +
    geom_point(alpha=0.8,size=2) +
    theme_bw()
tsnePlot

tsnePlot <- ggplot(pD.filtered, aes(x=tSNE1, y=tSNE2, color=log2(Acta2+1), shape=Replicate)) +
    geom_point(alpha=0.8,size=2) +
    theme_bw()
tsnePlot

tsnePlot <- ggplot(pD.filtered, aes(x=tSNE1, y=tSNE2, color=log2(Csn2+1), shape=Replicate)) +
    geom_point(alpha=0.8,size=2) +
    theme_bw()
tsnePlot

#tsnePlot based on cell Cycle
library(scLVM)
ens_ids_cc <- getEnsembl('GO:0007049')
sel <- rownames(m.norm) %in% ens_ids_cc
fPCA <- log2(t(m.norm[sel,])+1)
fPCA <- scale(fPCA,scale=TRUE,center=TRUE)
set.seed(rnd_seed)
tsn <- Rtsne(fPCA,perplexity=25)

pD.filtered$cc_tSNE1 <- tsn$Y[,1]
pD.filtered$cc_tSNE2 <- tsn$Y[,2]

tsnePlot <- ggplot(pD.filtered, aes(x=cc_tSNE1, y=cc_tSNE2, color=Condition, shape=Replicate)) +
    geom_point(alpha=0.8,size=2) +
    theme_bw()
tsnePlot
```
